apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations:
    # This annotation triggers the controller
    eni-tagger.io/tags: "CostCenter=1234,Team=Platform,Env=Dev"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
