apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-eni-tagger.fullname" . }}
  labels:
    {{- include "k8s-eni-tagger.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
{{- if eq (include "k8s-eni-tagger.leaderElectionEnabled" .) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-eni-tagger.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-eni-tagger.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-eni-tagger.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-eni-tagger.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-eni-tagger.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-eni-tagger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.config.enableCacheConfigMap }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-eni-tagger.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-eni-tagger.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-eni-tagger.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-eni-tagger.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-eni-tagger.fullname" . }}-cache
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-eni-tagger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-eni-tagger.fullname" . }}
  labels:
    {{- include "k8s-eni-tagger.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-eni-tagger.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-eni-tagger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
